### ISSUE TITLE
Wrong charset encoding in Gatsby packages hub?

### ISSUE THREAD

**Issue by apicinich** [progital/gatsby-wpgraphql-inline-images#11]
got some errors like `Error: Unable to find plugin "gatsby-wpgraphql-inline-images". Perhaps you nee  d to install its package?` and `An unexpected error occurred: "could not find a copy of gatsby to link in` after I ran in terminal (copy/paste) command from this page:
https://www.gatsbyjs.org/packages/gatsby-wpgraphql-inline-images/

**Comment by progital** [comment]
Please check the solution there https://github.com/progital/gatsby-wpgraphql-inline-images/issues/5
