### ISSUE TITLE
sourceParser turning &nbsp; into string

### ISSUE THREAD

**Issue by robmarshall** [progital/gatsby-wpgraphql-inline-images#12]
Hi,

After running some tests, I have found that the resolver seems to be turning `&nbsp;` entities into strings, meaning contentParser is making them visible to the end user.

I think this is due to Cheerio not decoding entities:
https://github.com/progital/gatsby-wpgraphql-inline-images/blob/6c360a75202e5f9bdff92a3f092e5290da42dcc2/src/sourceParser.js#L73

I can understand the confusion as here: https://cheerio.js.org/ the documentation says that decodeEntitites defaults to true, however looking at the in-depth documentation shows it actually defaults to false: https://github.com/fb55/htmlparser2/wiki/Parser-options#option-decodeentities

I am happy to add a PR unless there is a reason you have not included this?

Thanks

**Comment by progital** [comment]
Hi,
I seem to recall some issues with `&nbsp;` that I ignored. You are very welcome to test the solution and submit a PR. 
Thank you!

**Comment by robmarshall** [comment]
Fixed here: https://github.com/progital/gatsby-wpgraphql-inline-images/pull/13
