### ISSUE TITLE
My IDE tells me that there is no declaration file for the module 'gatsby-wpgraphql-inline-images'

### ISSUE THREAD

**Issue by sant-IA** [progital/gatsby-wpgraphql-inline-images#14]
`gatsby develop` doesn't return errors but my template pages don't have any image.

I try the method explained on the readme: 
```js
const pluginOptions = {
	wordPressUrl: `https://admin.mywordpress.domain/`,
	uploadsUrl: `https://admin.mywordpress.domain/wp/wp-content/uploads/`,
};
const content = data.wpGraphQl.page.content
```

and then: 
```jsx
<div>{contentParser({ content }, pluginOptions)}</div>
```

In the content rendered the text is ok, but images are not rendered, only their  at all. 
The browser console neither returns errors.

The only strange error was noted on my IDE (vscode) that tells me this (in a message by the import contentParser):

    import contentParser from 'gatsby-wpgraphql-inline-images';

> Non è stato trovato alcun file di dichiarazione per il modulo 'gatsby-wpgraphql-inline-images'.
>   Try `npm install @types/gatsby-wpgraphql-inline-images` if it exists or add a new declaration (.d.ts) file containing `declare module 'gatsby-wpgraphql-inline-images';`ts(7016)

---

This is my config on `gatsby-config`:

```js
{
	resolve: 'gatsby-wpgraphql-inline-images',
		options: {
		   wordPressUrl: 'https://admin.mywordpress.domain/',
			uploadsUrl: 'https://admin.mywordpress.domain/wp/wp-content/uploads/',
			processPostTypes: ['Page', 'Post'],
			graphqlTypeName: 'WordPressGraphQl',
			httpHeaders: {
			   Authorization: `Basic ${process.env.TOKEN_HTPASSWD}`,
			}
		},
},
```

**Comment by progital** [comment]
The error message probably means that you are using TypeScript and need to add a new declaration. I'd suggest dropping TypeScript and using a basic starter as a first step in debugging this issue.

**Comment by sant-IA** [comment]
I'm already using a basic starter (my theme is built above the basic starter). Honestly I don't even know what is TypeScript

**Comment by progital** [comment]
I'm not into TypeScript so I don't know much about it either. The error message is TypeScript-related but it may not be the reason for the issue you are experiencing.
I've added an experimental `debugOutput` parameter in the latest version. Setting it to true provides more logging in the console. Try it.

I'm going to rename the issue because there is not going to be any declaration file for the module as it's not needed. Could you clarify what your problem is? The description is a bit unclear.
> but images are not rendered, only their at all.

**Comment by sant-IA** [comment]
@progital 
Sorry for that, it was a typo. I mean that the images where not rendered, only their div with alt text or parameters but not the images.  
I digg into this issue enabling `debugOutput` as you suggested. The problem is related to the headers/permissions. I will create a new issue then.
