### ISSUE TITLE
Images are not downloaded due to permission with htpasswd: "URI not defined" error

### ISSUE THREAD

**Issue by sant-IA** [progital/gatsby-wpgraphql-inline-images#16]
It seems to me that the plugin is configured as expected, with the headers authorization in its place: 

#### **`gatsby-config.js`**
``` js
{
  resolve: 'gatsby-wpgraphql-inline-images',
  options: {
    debugOutput: true,
    wordPressUrl: 'https://admin.my-wordpress-site.com/',
    uploadsUrl: 'https://admin.my-wordpress-site.com/wp/wp-content/uploads/',
    processPostTypes: ['Page', 'Post'],
    graphqlTypeName: 'WordPressGraphQl',
    httpHeaders: {
      Authorization: `Basic ${process.env.TOKEN_HTPASSWD}`,
    },
  },
},
```

After that I'm calling the plugin inside the template of the page:

#### **`templates/pageLayout.js`**
``` js
const pluginOptions = {
	wordPressUrl: `https://admin.my-wordpress-site.com/`,
	uploadsUrl: `https://admin.my-wordpress-site.com/wp/wp-content/uploads/`,
}

const content = data.wpGraphQl.page.content

[...]

<Layout>
<main>
  <div>
    <h1 dangerouslySetInnerHTML={{ __html: data.wpGraphQl.page.title }} />
    <div>{contentParser({ content }, pluginOptions)}</div> 

[...]
```

The content is well rendered but the image markups it the same as when I use `dangerouslySetInnerHTML`: 

```html
<img 
  class="aligncenter size-large wp-image-240" 
  src="https://admin.my-wordpress-site.com/wp/wp-content/uploads/2018/10/Borgo00003-1024x768.jpg" 
  alt="" 
  srcset="https://admin.my-wordpress-site.com/wp/wp-content/uploads/2018/10/Borgo00003-1024x768.jpg 1024w, https://admin.my-wordpress-site.com/wp/wp-content/uploads/2018/10/Borgo00003-300x225.jpg 300w, https://admin.my-wordpress-site.com/wp/wp-content/uploads/2018/10/Borgo00003-768x576.jpg 768w, https://admin.my-wordpress-site.com/wp/wp-content/uploads/2018/10/Borgo00003.jpg 1200w" sizes="(max-width: 848px) 100vw, 848px" width="848" height="636">
```
(obviously the image is not displayed because the headless wordpress cms its protected by the htpasswd)

I presume that the images are not downloaded since I don't found them in the static folder.

This is the end part of the develop process in the shell when I activate `debugOutput`:
 
```shell
success run static queries - 1.296 s — 5/5 3.95 queries/second
>>> Entered contentResolver @ URI not defined, skipping
success Downloading remote files — 1/1 - 0.461 s
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
success Downloading remote files — 4/4 - 1.383 s
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
success Downloading remote files — 1/1 - 0.252 s
success run page queries - 3.981 s — 13/13 3.29 queries/second
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ URI not defined, skipping
success start webpack server - 2.393 s — 1/1 2.45 pages/second
 DONE  Compiled successfully in 9911ms

```

**Comment by progital** [comment]
Hi,
Could you try adding `uri` to all your queries that fetch `content`? It won't work without `uri` in the query.

**Comment by sant-IA** [comment]
> Hi,
> Could you try adding `uri` to all your queries that fetch `content`? It won't work without `uri` in the query.

Thanks! It works
```shell
success Generating image thumbnails — 84/84 - 10.419 s
>>> Entered contentResolver @ dove-dormire
>>> Entered contentResolver @ dove-mangiare
>>> Entered contentResolver @ murales
>>> Entered contentResolver @ festa-del-borgo
>>> Entered contentResolver @ 5-motivi-visitare-borgo
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ ponte-di-tiberio
>>> Entered contentResolver @ URI not defined, skipping
>>> Entered contentResolver @ dove-dormire
>>> Entered contentResolver @ dove-mangiare
>>> Entered contentResolver @ festa-del-borgo
>>> Entered contentResolver @ ponte-di-tiberio
>>> Entered contentResolver @ murales
>>> Entered contentResolver @ 5-motivi-visitare-borgo
```
May I ask you why? I didn't saw that condition on the readme files (nor in the gatsby docs).



PS: besides, should I need pluginOptions object inside the page? I already have set the wordPressUrl and the uploadsUrl on the gatsby-config file, but when I set `<div>{contentParser({ content }, { wordPressUrl, uploadsUrl })}</div>` it tells me that wordPressUrl, uploadsUrl are not defined. Should I create a new issue?

**Comment by progital** [comment]
Glad that it helped. You still have a couple of `URI not defined` messages so you may want to look into that.

> May I ask you why? I didn't saw that condition on the readme files (nor in the gatsby docs).

My bad. I will amend the docs. `uri` is needed for caching downloaded images and content between multiple requests.

> besides, should I need pluginOptions object inside the page? I already have set the wordPressUrl and the uploadsUrl on the gatsby-config file

You need some way of passing your plugin options to your component. The readme suggests copying those options in all the components for simplicity and brevity. You may use "prop drilling" or context API as alternative solutions.

**Comment by sant-IA** [comment]
@progital thanks! I solve also the remained `URI not defined`, they come from the homepage. 

I'm now noticing that the images get downloaded twice, specially in the building phase. Is that normal? 

EDIT: maybe it's because I'm quering this images with `...GatsbyImageSharpFluid_tracedSVG` and `src` one, could it be that?:

```graphql
  query PagineWordpressGraphQl($id: ID!) {
    wpGraphQl {
      page(id: $id) {
        title
        seo {
          title
          metaDesc
        }
        acf_wpgraphql_imgCopertina {
          imgCopertina {
            altText
            sourceUrl
            imageFile {
              childImageSharp {
                fluid(maxWidth: 1400) {
                  ...GatsbyImageSharpFluid_tracedSVG
                  src
                }
              }
            }
          }
        }
        content
        uri
      }
    }
  }
```

**Comment by progital** [comment]
ACF image fields are completely independent from the images in content blocks. This plugin only handles images in `content`.
