### ISSUE TITLE
TypeError: breakpoints.map is not a function

### ISSUE THREAD

**Issue by ravinggenius** [progital/gatsby-wpgraphql-inline-images#19]
The content parser replaces WordPress `<a />` with Gatsby's `<Link />`, uses `Styled.a` from `theme-ui`. `theme-ui` extends `styled-system`, which seems to expect a `ThemeProvider` to be configured. My project doesn't use or need `theme-ui` or `styled-system`, so when I call `contentParser`; I get a long, confusing stack trace.

https://github.com/progital/gatsby-wpgraphql-inline-images/blob/246a4d53ed9288f98d98500610e4660e4c9a5ce1/src/contentParser.js#L66-L68 seems to be causing the trouble. I'm guessing these libraries (`theme-ui`, `styled-system`) are not really required for `gatsby-wpgraphql-inline-images` to operate correctly. Would you be interested in removing them as dependencies? I'm happy to open a pull request.

Edit: typo fix

**Comment by progital** [comment]
I've never considered using the plugin without `theme-ui` because I use it for styling those context blocks (and everything else). Let me test how it would work without `theme-ui`. If you've already tried and can submit a PR - it's always welcome!

**Comment by progital** [comment]
I'm not planning to drop `theme-ui` now so I'm closing this issue. In the future major release (**if** it happens) all the unneeded dependencies will be dropped.
