### ISSUE TITLE
Installing the plugin with Yarn fails on W10

### ISSUE THREAD

**Issue by bonakor** [progital/gatsby-wpgraphql-inline-images#26]
Hi,
I'm trying to install the plugin with W10, and it fails saying An unexpected error occurred: 
```could not find a copy of gatsby to link in ...\\node_modules\\gatsby-wpgraphql-inline-images
\\node_modules".```

When I install the plugin with npm, it works but then launching "gatsby develop" bugs, saying 

```
`Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
```

Would you have an idea of what to do (but I'm guessing your plugin might be merged into the new version of GatsbyWp :/)

**Comment by progital** [comment]
Hi,

You're absolutely right, the new wordpress source plugin is very likely to make this plugin redundant so I'm sitting tight until the release.
Regarding this issue - you are not the only one who had similar problems. Check out https://github.com/progital/gatsby-wpgraphql-inline-images/issues/5 . I recommend deleting all `lock` files and node_modules and then re-installing everything.

**Comment by bonakor** [comment]
Damn, #5 it was me. I'm sorry for that 

And okay for the next WP source plugin

**Comment by progital** [comment]
I haven't noticed that it was you. :)
