### ISSUE TITLE
FeaturedImage implementation

### ISSUE THREAD

**Issue by jacobarriola** [progital/gatsby-wpgraphql-inline-images#3]
Hi there!

I'm getting the following error message for all my image requests when firing up `gatsby develop`.

My local WP site is proxying the images from production, so not sure if that has anything to do with my issue. However, I was able to reproduce the issue on a fresh gatsby-hello-world and a fresh wp install with a local image.

```
Exception featured image TypeError: Cannot read property 'toLowerCase' of undefined
    at healOptions (/node_modules/gatsby-plugin-sharp/plugin-options.js:51:38)
    at fluid (/node_modules/gatsby-plugin-sharp/index.js:296:19)
    at convertFileNodeToFluid (/node_modules/gatsby-wpgraphql-inline-images/src/utils.js:78:27)
    at downloadImage (/node_modules/gatsby-wpgraphql-inline-images/src/utils.js:60:29)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.featuredImageResolver [as resolve] (/node_modules/gatsby-wpgraphql-inline-images/gatsby-node.js:102:19)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

query 
```graphql
query {
    wordpress {
      portfolios {
        nodes {
          title
          featuredImage {
            srcSet
            sizes
            sourceUrl
            content
          }
        }
      }
    }
  }
```

**Comment by progital** [comment]
Hey!

This error is triggered when a file extension is missing. Do you have any file names without extension?
Could you share your test case so I can run it myself?

**Comment by jacobarriola** [comment]
> Do you have any file names without extension?

That's what I thought as well, but my WP install only has one image in there, and it has a .jpg extension

![image](https://user-images.githubusercontent.com/1371573/62549637-b7e03f80-b81d-11e9-9860-afda7e31fa65.png)

>Could you share your test case so I can run it myself?

Not sure what you mean by that. Could you be a bit more specific :)

**Comment by progital** [comment]
@henrikwirth recently posted a better solution on wpgrahql slack. I'm planning to deprecate my handling of featuredImage in favor of that solution. Would you mind checking if it works for you?

**Comment by henrikwirth** [comment]
I created a gist for it here: https://gist.github.com/henrikwirth/4ba900b7f89b9e28ec81497466b12710

Also checkout this:
https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image
or
https://dev.to/nevernull/gatsby-with-wpgraphql-acf-and-gatbsy-image-72m

**Comment by jacobarriola** [comment]
@progital for sure. I'll check later this afternoon. 👍

**Comment by jacobarriola** [comment]
@henrikwirth your resolver worked for me. Thanks!
