### ISSUE TITLE
Anchors

### ISSUE THREAD

**Issue by jaykeny** [progital/gatsby-wpgraphql-inline-images#31]
Amazing plugin, but I did notice it doesn't work with anchor tags, any plans to incorporate?

**Comment by jaykeny** [comment]
I fixed the issue, but I don't have PR access. Below is the modified contentParser.js
[contentParser.zip](https://github.com/progital/gatsby-wpgraphql-inline-images/files/4642907/contentParser.zip)

**Comment by progital** [comment]
Thank you. Could you create an actual PR? I haven't granted anyone any special access rights and I received PRs before. For example https://github.com/progital/gatsby-wpgraphql-inline-images/pull/30

**Comment by jaykeny** [comment]
PR done. Thank you!
