### ISSUE TITLE
Issue when adding the plugin

### ISSUE THREAD

**Issue by bonakor** [progital/gatsby-wpgraphql-inline-images#5]
Hello,
I'm trying to add the plugin to an install.

It tells me 
`error An unexpected error occurred: "could not find a copy of gatsby to link in /mnt/c/Users/USERSESSION/SITENAME/node_modules/gatsby-wpgraphql-inline-images/node_modules".`

Adding other plugins works normally.

My repo is there if needed https://github.com/bonakor/nuuksby/

Let me know if I can give more infos :)

**Comment by progital** [comment]
Hey,
Deleting `yarn.lock` fixes it for me. This is something I'd love to look into when I have time but at the moment deleting lock files should help.

**Comment by bonakor** [comment]
Hey!
I tried deleting the yarn.lock and it worked. Thank you.

**Comment by robmarshall** [comment]
Just came across this as well.
