### ISSUE TITLE
Feature Request: Headers in Download Image

### ISSUE THREAD

**Issue by robmarshall** [progital/gatsby-wpgraphql-inline-images#6]
The plugin is not able to download any images from WP sites behind basic auth, or that require specific header tokens to access files.

WpGraphQL currently does this by allowing a headers option to be passed in via the config file. This may be the best way of doing this?

This header variable can then be passed to the CreateRemoteFileNode function. https://github.com/progital/gatsby-wpgraphql-inline-images/blob/335880dd0562e7d8ea0c2b8c37e3a6a6f5dab8eb/src/utils.js#L13

See: HTTP Headers in the CreateRemoteFleNode documentation: https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode

**Comment by progital** [comment]
Good idea. Will do.

**Comment by progital** [comment]
Thank you for the PR. Would it make sense to add htaccess authentication as well?

**Comment by robmarshall** [comment]
Basic auth can be be passed via headers using - Authentication: "Basic *thenstringhere*", so not completely necessary. Could just be explained in the readme?

**Comment by progital** [comment]
Ok, then let's leave it as it is now. It's not so common use case to add it to the readme.
