### ISSUE TITLE
Question: downloadImage function

### ISSUE THREAD

**Issue by robmarshall** [progital/gatsby-wpgraphql-inline-images#9]
Hi,

The downloadImage function is included in utils.js

 https://github.com/progital/gatsby-wpgraphql-inline-images/blob/6c360a75202e5f9bdff92a3f092e5290da42dcc2/src/utils.js#L29

But is not referenced in the readme, or used within the plugin. Is this an oversight, or is it to be used in a future version? I am working through a problem I am having with the package and came across it.

Cheers

**Comment by progital** [comment]
Hi,

Good catch. It was used for handling featured image and I didn't remove it.
https://github.com/progital/gatsby-wpgraphql-inline-images/commit/b8ffe156d6ff93b5d9e839a6c73134a82b8f2b8c
The commit that removed its usage.
